version: '2'
services:
   wordpress:
     image: wordpress:latest
     ports:
       - "8082:80"
     environment:
       WORDPRESS_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_USER_PASSWORD: wordpress
     restart: always
     depends_on:
       - mysql

   mysql:
     image: mysql:latest
     ports:
       - "3308:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     restart: always

